// Code generated by "openapi-codegen"; DO NOT EDIT.
/*
 * OneLogin API
 *
 * This is an administrative API for OneLogin customers
 *
 * API version: 1.1.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"encoding/json"
)

// UserMfaFactorsResponse struct for UserMfaFactorsResponse
type UserMfaFactorsResponse struct {
	Status *Status                     `json:"status,omitempty"`
	Data   *UserMfaFactorsResponseData `json:"data,omitempty"`
}

// NewUserMfaFactorsResponse instantiates a new UserMfaFactorsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserMfaFactorsResponse() *UserMfaFactorsResponse {
	this := UserMfaFactorsResponse{}
	return &this
}

// NewUserMfaFactorsResponseWithDefaults instantiates a new UserMfaFactorsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserMfaFactorsResponseWithDefaults() *UserMfaFactorsResponse {
	this := UserMfaFactorsResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UserMfaFactorsResponse) GetStatus() Status {
	if o == nil || o.Status == nil {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserMfaFactorsResponse) GetStatusOk() (*Status, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UserMfaFactorsResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *UserMfaFactorsResponse) SetStatus(v Status) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UserMfaFactorsResponse) GetData() UserMfaFactorsResponseData {
	if o == nil || o.Data == nil {
		var ret UserMfaFactorsResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserMfaFactorsResponse) GetDataOk() (*UserMfaFactorsResponseData, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UserMfaFactorsResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given UserMfaFactorsResponseData and assigns it to the Data field.
func (o *UserMfaFactorsResponse) SetData(v UserMfaFactorsResponseData) {
	o.Data = &v
}

func (o UserMfaFactorsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableUserMfaFactorsResponse struct {
	value *UserMfaFactorsResponse
	isSet bool
}

func (v NullableUserMfaFactorsResponse) Get() *UserMfaFactorsResponse {
	return v.value
}

func (v *NullableUserMfaFactorsResponse) Set(val *UserMfaFactorsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserMfaFactorsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserMfaFactorsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserMfaFactorsResponse(val *UserMfaFactorsResponse) *NullableUserMfaFactorsResponse {
	return &NullableUserMfaFactorsResponse{value: val, isSet: true}
}

func (v NullableUserMfaFactorsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserMfaFactorsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
