// Code generated by "openapi-codegen"; DO NOT EDIT.
/*
 * OneLogin API
 *
 * This is an administrative API for OneLogin customers
 *
 * API version: 1.1.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"encoding/json"
	"github.com/yacchi/go-onelogin-oas/models"
)

// UserLoginResponse struct for UserLoginResponse
type UserLoginResponse struct {
	Status *Status `json:"status,omitempty"`
	Data *Response `json:"data,omitempty"`
}

// NewUserLoginResponse instantiates a new UserLoginResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUserLoginResponse() *UserLoginResponse {
	this := UserLoginResponse{}
	return &this
}

// NewUserLoginResponseWithDefaults instantiates a new UserLoginResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUserLoginResponseWithDefaults() *UserLoginResponse {
	this := UserLoginResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *UserLoginResponse) GetStatus() Status {
	if o == nil || o.Status == nil {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserLoginResponse) GetStatusOk() (*Status, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *UserLoginResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *UserLoginResponse) SetStatus(v Status) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UserLoginResponse) GetData() Response {
	if o == nil || o.Data == nil {
		var ret Response
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UserLoginResponse) GetDataOk() (*Response, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UserLoginResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given Response and assigns it to the Data field.
func (o *UserLoginResponse) SetData(v Response) {
	o.Data = &v
}

func (o UserLoginResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableUserLoginResponse struct {
	value *UserLoginResponse
	isSet bool
}

func (v NullableUserLoginResponse) Get() *UserLoginResponse {
	return v.value
}

func (v *NullableUserLoginResponse) Set(val *UserLoginResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUserLoginResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUserLoginResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUserLoginResponse(val *UserLoginResponse) *NullableUserLoginResponse {
	return &NullableUserLoginResponse{value: val, isSet: true}
}

func (v NullableUserLoginResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUserLoginResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
