// Code generated by "openapi-codegen"; DO NOT EDIT.
/*
 * OneLogin API
 *
 * This is an administrative API for OneLogin customers
 *
 * API version: 1.1.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"encoding/json"
)

// InlineObject10 struct for InlineObject10
type InlineObject10 struct {
	// The identifier of the factor to enroll the user with
	FactorId int32 `json:"factor_id"`
	// A name for the users device
	DisplayName string `json:"display_name"`
	// The phone number of the user in E.164 format.
	Number string `json:"number"`
}

// NewInlineObject10 instantiates a new InlineObject10 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject10(factorId int32, displayName string, number string, ) *InlineObject10 {
	this := InlineObject10{}
	this.FactorId = factorId
	this.DisplayName = displayName
	this.Number = number
	return &this
}

// NewInlineObject10WithDefaults instantiates a new InlineObject10 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject10WithDefaults() *InlineObject10 {
	this := InlineObject10{}
	return &this
}

// GetFactorId returns the FactorId field value
func (o *InlineObject10) GetFactorId() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.FactorId
}

// GetFactorIdOk returns a tuple with the FactorId field value
// and a boolean to check if the value has been set.
func (o *InlineObject10) GetFactorIdOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FactorId, true
}

// SetFactorId sets field value
func (o *InlineObject10) SetFactorId(v int32) {
	o.FactorId = v
}

// GetDisplayName returns the DisplayName field value
func (o *InlineObject10) GetDisplayName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value
// and a boolean to check if the value has been set.
func (o *InlineObject10) GetDisplayNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DisplayName, true
}

// SetDisplayName sets field value
func (o *InlineObject10) SetDisplayName(v string) {
	o.DisplayName = v
}

// GetNumber returns the Number field value
func (o *InlineObject10) GetNumber() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Number
}

// GetNumberOk returns a tuple with the Number field value
// and a boolean to check if the value has been set.
func (o *InlineObject10) GetNumberOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Number, true
}

// SetNumber sets field value
func (o *InlineObject10) SetNumber(v string) {
	o.Number = v
}

func (o InlineObject10) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["factor_id"] = o.FactorId
	}
	if true {
		toSerialize["display_name"] = o.DisplayName
	}
	if true {
		toSerialize["number"] = o.Number
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject10 struct {
	value *InlineObject10
	isSet bool
}

func (v NullableInlineObject10) Get() *InlineObject10 {
	return v.value
}

func (v *NullableInlineObject10) Set(val *InlineObject10) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject10) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject10) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject10(val *InlineObject10) *NullableInlineObject10 {
	return &NullableInlineObject10{value: val, isSet: true}
}

func (v NullableInlineObject10) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject10) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
