// Code generated by "openapi-codegen"; DO NOT EDIT.
/*
 * OneLogin API
 *
 * This is an administrative API for OneLogin customers
 *
 * API version: 1.1.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"encoding/json"
)

// AppParameters struct for AppParameters
type AppParameters struct {
	Id                        *int32  `json:"id,omitempty"`
	Label                     *string `json:"label,omitempty"`
	UserAttributeMappings     *string `json:"user_attribute_mappings,omitempty"`
	UserAttributeMacros       *string `json:"user_attribute_macros,omitempty"`
	AttributesTransformations *string `json:"attributes_transformations,omitempty"`
	SkipIfBlank               *bool   `json:"skip_if_blank,omitempty"`
	Values                    *string `json:"values,omitempty"`
	DefaultValues             *string `json:"default_values,omitempty"`
	ProvisionedEntitlements   *bool   `json:"provisioned_entitlements,omitempty"`
	SafeEntitlementsEnabled   *bool   `json:"safe_entitlements_enabled,omitempty"`
}

// NewAppParameters instantiates a new AppParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppParameters() *AppParameters {
	this := AppParameters{}
	return &this
}

// NewAppParametersWithDefaults instantiates a new AppParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppParametersWithDefaults() *AppParameters {
	this := AppParameters{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AppParameters) GetId() int32 {
	if o == nil || o.Id == nil {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppParameters) GetIdOk() (*int32, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AppParameters) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *AppParameters) SetId(v int32) {
	o.Id = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *AppParameters) GetLabel() string {
	if o == nil || o.Label == nil {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppParameters) GetLabelOk() (*string, bool) {
	if o == nil || o.Label == nil {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *AppParameters) HasLabel() bool {
	if o != nil && o.Label != nil {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *AppParameters) SetLabel(v string) {
	o.Label = &v
}

// GetUserAttributeMappings returns the UserAttributeMappings field value if set, zero value otherwise.
func (o *AppParameters) GetUserAttributeMappings() string {
	if o == nil || o.UserAttributeMappings == nil {
		var ret string
		return ret
	}
	return *o.UserAttributeMappings
}

// GetUserAttributeMappingsOk returns a tuple with the UserAttributeMappings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppParameters) GetUserAttributeMappingsOk() (*string, bool) {
	if o == nil || o.UserAttributeMappings == nil {
		return nil, false
	}
	return o.UserAttributeMappings, true
}

// HasUserAttributeMappings returns a boolean if a field has been set.
func (o *AppParameters) HasUserAttributeMappings() bool {
	if o != nil && o.UserAttributeMappings != nil {
		return true
	}

	return false
}

// SetUserAttributeMappings gets a reference to the given string and assigns it to the UserAttributeMappings field.
func (o *AppParameters) SetUserAttributeMappings(v string) {
	o.UserAttributeMappings = &v
}

// GetUserAttributeMacros returns the UserAttributeMacros field value if set, zero value otherwise.
func (o *AppParameters) GetUserAttributeMacros() string {
	if o == nil || o.UserAttributeMacros == nil {
		var ret string
		return ret
	}
	return *o.UserAttributeMacros
}

// GetUserAttributeMacrosOk returns a tuple with the UserAttributeMacros field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppParameters) GetUserAttributeMacrosOk() (*string, bool) {
	if o == nil || o.UserAttributeMacros == nil {
		return nil, false
	}
	return o.UserAttributeMacros, true
}

// HasUserAttributeMacros returns a boolean if a field has been set.
func (o *AppParameters) HasUserAttributeMacros() bool {
	if o != nil && o.UserAttributeMacros != nil {
		return true
	}

	return false
}

// SetUserAttributeMacros gets a reference to the given string and assigns it to the UserAttributeMacros field.
func (o *AppParameters) SetUserAttributeMacros(v string) {
	o.UserAttributeMacros = &v
}

// GetAttributesTransformations returns the AttributesTransformations field value if set, zero value otherwise.
func (o *AppParameters) GetAttributesTransformations() string {
	if o == nil || o.AttributesTransformations == nil {
		var ret string
		return ret
	}
	return *o.AttributesTransformations
}

// GetAttributesTransformationsOk returns a tuple with the AttributesTransformations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppParameters) GetAttributesTransformationsOk() (*string, bool) {
	if o == nil || o.AttributesTransformations == nil {
		return nil, false
	}
	return o.AttributesTransformations, true
}

// HasAttributesTransformations returns a boolean if a field has been set.
func (o *AppParameters) HasAttributesTransformations() bool {
	if o != nil && o.AttributesTransformations != nil {
		return true
	}

	return false
}

// SetAttributesTransformations gets a reference to the given string and assigns it to the AttributesTransformations field.
func (o *AppParameters) SetAttributesTransformations(v string) {
	o.AttributesTransformations = &v
}

// GetSkipIfBlank returns the SkipIfBlank field value if set, zero value otherwise.
func (o *AppParameters) GetSkipIfBlank() bool {
	if o == nil || o.SkipIfBlank == nil {
		var ret bool
		return ret
	}
	return *o.SkipIfBlank
}

// GetSkipIfBlankOk returns a tuple with the SkipIfBlank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppParameters) GetSkipIfBlankOk() (*bool, bool) {
	if o == nil || o.SkipIfBlank == nil {
		return nil, false
	}
	return o.SkipIfBlank, true
}

// HasSkipIfBlank returns a boolean if a field has been set.
func (o *AppParameters) HasSkipIfBlank() bool {
	if o != nil && o.SkipIfBlank != nil {
		return true
	}

	return false
}

// SetSkipIfBlank gets a reference to the given bool and assigns it to the SkipIfBlank field.
func (o *AppParameters) SetSkipIfBlank(v bool) {
	o.SkipIfBlank = &v
}

// GetValues returns the Values field value if set, zero value otherwise.
func (o *AppParameters) GetValues() string {
	if o == nil || o.Values == nil {
		var ret string
		return ret
	}
	return *o.Values
}

// GetValuesOk returns a tuple with the Values field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppParameters) GetValuesOk() (*string, bool) {
	if o == nil || o.Values == nil {
		return nil, false
	}
	return o.Values, true
}

// HasValues returns a boolean if a field has been set.
func (o *AppParameters) HasValues() bool {
	if o != nil && o.Values != nil {
		return true
	}

	return false
}

// SetValues gets a reference to the given string and assigns it to the Values field.
func (o *AppParameters) SetValues(v string) {
	o.Values = &v
}

// GetDefaultValues returns the DefaultValues field value if set, zero value otherwise.
func (o *AppParameters) GetDefaultValues() string {
	if o == nil || o.DefaultValues == nil {
		var ret string
		return ret
	}
	return *o.DefaultValues
}

// GetDefaultValuesOk returns a tuple with the DefaultValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppParameters) GetDefaultValuesOk() (*string, bool) {
	if o == nil || o.DefaultValues == nil {
		return nil, false
	}
	return o.DefaultValues, true
}

// HasDefaultValues returns a boolean if a field has been set.
func (o *AppParameters) HasDefaultValues() bool {
	if o != nil && o.DefaultValues != nil {
		return true
	}

	return false
}

// SetDefaultValues gets a reference to the given string and assigns it to the DefaultValues field.
func (o *AppParameters) SetDefaultValues(v string) {
	o.DefaultValues = &v
}

// GetProvisionedEntitlements returns the ProvisionedEntitlements field value if set, zero value otherwise.
func (o *AppParameters) GetProvisionedEntitlements() bool {
	if o == nil || o.ProvisionedEntitlements == nil {
		var ret bool
		return ret
	}
	return *o.ProvisionedEntitlements
}

// GetProvisionedEntitlementsOk returns a tuple with the ProvisionedEntitlements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppParameters) GetProvisionedEntitlementsOk() (*bool, bool) {
	if o == nil || o.ProvisionedEntitlements == nil {
		return nil, false
	}
	return o.ProvisionedEntitlements, true
}

// HasProvisionedEntitlements returns a boolean if a field has been set.
func (o *AppParameters) HasProvisionedEntitlements() bool {
	if o != nil && o.ProvisionedEntitlements != nil {
		return true
	}

	return false
}

// SetProvisionedEntitlements gets a reference to the given bool and assigns it to the ProvisionedEntitlements field.
func (o *AppParameters) SetProvisionedEntitlements(v bool) {
	o.ProvisionedEntitlements = &v
}

// GetSafeEntitlementsEnabled returns the SafeEntitlementsEnabled field value if set, zero value otherwise.
func (o *AppParameters) GetSafeEntitlementsEnabled() bool {
	if o == nil || o.SafeEntitlementsEnabled == nil {
		var ret bool
		return ret
	}
	return *o.SafeEntitlementsEnabled
}

// GetSafeEntitlementsEnabledOk returns a tuple with the SafeEntitlementsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppParameters) GetSafeEntitlementsEnabledOk() (*bool, bool) {
	if o == nil || o.SafeEntitlementsEnabled == nil {
		return nil, false
	}
	return o.SafeEntitlementsEnabled, true
}

// HasSafeEntitlementsEnabled returns a boolean if a field has been set.
func (o *AppParameters) HasSafeEntitlementsEnabled() bool {
	if o != nil && o.SafeEntitlementsEnabled != nil {
		return true
	}

	return false
}

// SetSafeEntitlementsEnabled gets a reference to the given bool and assigns it to the SafeEntitlementsEnabled field.
func (o *AppParameters) SetSafeEntitlementsEnabled(v bool) {
	o.SafeEntitlementsEnabled = &v
}

func (o AppParameters) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Label != nil {
		toSerialize["label"] = o.Label
	}
	if o.UserAttributeMappings != nil {
		toSerialize["user_attribute_mappings"] = o.UserAttributeMappings
	}
	if o.UserAttributeMacros != nil {
		toSerialize["user_attribute_macros"] = o.UserAttributeMacros
	}
	if o.AttributesTransformations != nil {
		toSerialize["attributes_transformations"] = o.AttributesTransformations
	}
	if o.SkipIfBlank != nil {
		toSerialize["skip_if_blank"] = o.SkipIfBlank
	}
	if o.Values != nil {
		toSerialize["values"] = o.Values
	}
	if o.DefaultValues != nil {
		toSerialize["default_values"] = o.DefaultValues
	}
	if o.ProvisionedEntitlements != nil {
		toSerialize["provisioned_entitlements"] = o.ProvisionedEntitlements
	}
	if o.SafeEntitlementsEnabled != nil {
		toSerialize["safe_entitlements_enabled"] = o.SafeEntitlementsEnabled
	}
	return json.Marshal(toSerialize)
}

type NullableAppParameters struct {
	value *AppParameters
	isSet bool
}

func (v NullableAppParameters) Get() *AppParameters {
	return v.value
}

func (v *NullableAppParameters) Set(val *AppParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableAppParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableAppParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppParameters(val *AppParameters) *NullableAppParameters {
	return &NullableAppParameters{value: val, isSet: true}
}

func (v NullableAppParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
