// Code generated by "openapi-codegen"; DO NOT EDIT.
/*
 * OneLogin API
 *
 * This is an administrative API for OneLogin customers
 *
 * API version: 1.1.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"encoding/json"
)

// InlineObject9 struct for InlineObject9
type InlineObject9 struct {
	// Provide the MFA device_id you are submitting for verification.
	AppId int32 `json:"app_id"`
	// Provide the MFA device_id you are submitting for verification.
	DeviceId int32 `json:"device_id"`
	// Provide the state_token associated with the MFA device_id you are submitting for verification.
	StateToken string `json:"state_token"`
	// Provide the OTP value for the MFA factor you are submitting for verification.
	OtpToken *string `json:"otp_token,omitempty"`
	// When verifying MFA via Protect Push, set this to true to stop additional push notifications being sent to the OneLogin Protect device.
	DoNotNotify *bool `json:"do_not_notify,omitempty"`
}

// NewInlineObject9 instantiates a new InlineObject9 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject9(appId int32, deviceId int32, stateToken string) *InlineObject9 {
	this := InlineObject9{}
	this.AppId = appId
	this.DeviceId = deviceId
	this.StateToken = stateToken
	var doNotNotify bool = false
	this.DoNotNotify = &doNotNotify
	return &this
}

// NewInlineObject9WithDefaults instantiates a new InlineObject9 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject9WithDefaults() *InlineObject9 {
	this := InlineObject9{}
	var doNotNotify bool = false
	this.DoNotNotify = &doNotNotify
	return &this
}

// GetAppId returns the AppId field value
func (o *InlineObject9) GetAppId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value
// and a boolean to check if the value has been set.
func (o *InlineObject9) GetAppIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppId, true
}

// SetAppId sets field value
func (o *InlineObject9) SetAppId(v int32) {
	o.AppId = v
}

// GetDeviceId returns the DeviceId field value
func (o *InlineObject9) GetDeviceId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.DeviceId
}

// GetDeviceIdOk returns a tuple with the DeviceId field value
// and a boolean to check if the value has been set.
func (o *InlineObject9) GetDeviceIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DeviceId, true
}

// SetDeviceId sets field value
func (o *InlineObject9) SetDeviceId(v int32) {
	o.DeviceId = v
}

// GetStateToken returns the StateToken field value
func (o *InlineObject9) GetStateToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.StateToken
}

// GetStateTokenOk returns a tuple with the StateToken field value
// and a boolean to check if the value has been set.
func (o *InlineObject9) GetStateTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StateToken, true
}

// SetStateToken sets field value
func (o *InlineObject9) SetStateToken(v string) {
	o.StateToken = v
}

// GetOtpToken returns the OtpToken field value if set, zero value otherwise.
func (o *InlineObject9) GetOtpToken() string {
	if o == nil || o.OtpToken == nil {
		var ret string
		return ret
	}
	return *o.OtpToken
}

// GetOtpTokenOk returns a tuple with the OtpToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject9) GetOtpTokenOk() (*string, bool) {
	if o == nil || o.OtpToken == nil {
		return nil, false
	}
	return o.OtpToken, true
}

// HasOtpToken returns a boolean if a field has been set.
func (o *InlineObject9) HasOtpToken() bool {
	if o != nil && o.OtpToken != nil {
		return true
	}

	return false
}

// SetOtpToken gets a reference to the given string and assigns it to the OtpToken field.
func (o *InlineObject9) SetOtpToken(v string) {
	o.OtpToken = &v
}

// GetDoNotNotify returns the DoNotNotify field value if set, zero value otherwise.
func (o *InlineObject9) GetDoNotNotify() bool {
	if o == nil || o.DoNotNotify == nil {
		var ret bool
		return ret
	}
	return *o.DoNotNotify
}

// GetDoNotNotifyOk returns a tuple with the DoNotNotify field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject9) GetDoNotNotifyOk() (*bool, bool) {
	if o == nil || o.DoNotNotify == nil {
		return nil, false
	}
	return o.DoNotNotify, true
}

// HasDoNotNotify returns a boolean if a field has been set.
func (o *InlineObject9) HasDoNotNotify() bool {
	if o != nil && o.DoNotNotify != nil {
		return true
	}

	return false
}

// SetDoNotNotify gets a reference to the given bool and assigns it to the DoNotNotify field.
func (o *InlineObject9) SetDoNotNotify(v bool) {
	o.DoNotNotify = &v
}

func (o InlineObject9) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["app_id"] = o.AppId
	}
	if true {
		toSerialize["device_id"] = o.DeviceId
	}
	if true {
		toSerialize["state_token"] = o.StateToken
	}
	if o.OtpToken != nil {
		toSerialize["otp_token"] = o.OtpToken
	}
	if o.DoNotNotify != nil {
		toSerialize["do_not_notify"] = o.DoNotNotify
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject9 struct {
	value *InlineObject9
	isSet bool
}

func (v NullableInlineObject9) Get() *InlineObject9 {
	return v.value
}

func (v *NullableInlineObject9) Set(val *InlineObject9) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject9) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject9) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject9(val *InlineObject9) *NullableInlineObject9 {
	return &NullableInlineObject9{value: val, isSet: true}
}

func (v NullableInlineObject9) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject9) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
