// Code generated by "openapi-codegen"; DO NOT EDIT.
/*
 * OneLogin API
 *
 * This is an administrative API for OneLogin customers
 *
 * API version: 1.1.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"encoding/json"
)

// EnrollMfaDeviceResponse struct for EnrollMfaDeviceResponse
type EnrollMfaDeviceResponse struct {
	Status *Status      `json:"status,omitempty"`
	Data   *[]MfaDevice `json:"data,omitempty"`
}

// NewEnrollMfaDeviceResponse instantiates a new EnrollMfaDeviceResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnrollMfaDeviceResponse() *EnrollMfaDeviceResponse {
	this := EnrollMfaDeviceResponse{}
	return &this
}

// NewEnrollMfaDeviceResponseWithDefaults instantiates a new EnrollMfaDeviceResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnrollMfaDeviceResponseWithDefaults() *EnrollMfaDeviceResponse {
	this := EnrollMfaDeviceResponse{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *EnrollMfaDeviceResponse) GetStatus() Status {
	if o == nil || o.Status == nil {
		var ret Status
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrollMfaDeviceResponse) GetStatusOk() (*Status, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *EnrollMfaDeviceResponse) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given Status and assigns it to the Status field.
func (o *EnrollMfaDeviceResponse) SetStatus(v Status) {
	o.Status = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *EnrollMfaDeviceResponse) GetData() []MfaDevice {
	if o == nil || o.Data == nil {
		var ret []MfaDevice
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EnrollMfaDeviceResponse) GetDataOk() (*[]MfaDevice, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *EnrollMfaDeviceResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given []MfaDevice and assigns it to the Data field.
func (o *EnrollMfaDeviceResponse) SetData(v []MfaDevice) {
	o.Data = &v
}

func (o EnrollMfaDeviceResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableEnrollMfaDeviceResponse struct {
	value *EnrollMfaDeviceResponse
	isSet bool
}

func (v NullableEnrollMfaDeviceResponse) Get() *EnrollMfaDeviceResponse {
	return v.value
}

func (v *NullableEnrollMfaDeviceResponse) Set(val *EnrollMfaDeviceResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEnrollMfaDeviceResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEnrollMfaDeviceResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnrollMfaDeviceResponse(val *EnrollMfaDeviceResponse) *NullableEnrollMfaDeviceResponse {
	return &NullableEnrollMfaDeviceResponse{value: val, isSet: true}
}

func (v NullableEnrollMfaDeviceResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnrollMfaDeviceResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
