// Code generated by "openapi-codegen"; DO NOT EDIT.
/*
 * OneLogin API
 *
 * This is an administrative API for OneLogin customers
 *
 * API version: 1.1.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"encoding/json"
)

// InlineObject5 struct for InlineObject5
type InlineObject5 struct {
	// The new password 
	Password string `json:"password"`
	// The new password repeated
	PasswordConfirmation string `json:"password_confirmation"`
	// Set to salt+sha256.
	PasswordAlgorithm string `json:"password_algorithm"`
	// If your password hash has been salted then you can provide the salt used in this param.
	PasswordSalt *string `json:"password_salt,omitempty"`
}

// NewInlineObject5 instantiates a new InlineObject5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject5(password string, passwordConfirmation string, passwordAlgorithm string, ) *InlineObject5 {
	this := InlineObject5{}
	this.Password = password
	this.PasswordConfirmation = passwordConfirmation
	this.PasswordAlgorithm = passwordAlgorithm
	return &this
}

// NewInlineObject5WithDefaults instantiates a new InlineObject5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject5WithDefaults() *InlineObject5 {
	this := InlineObject5{}
	return &this
}

// GetPassword returns the Password field value
func (o *InlineObject5) GetPassword() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *InlineObject5) GetPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *InlineObject5) SetPassword(v string) {
	o.Password = v
}

// GetPasswordConfirmation returns the PasswordConfirmation field value
func (o *InlineObject5) GetPasswordConfirmation() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.PasswordConfirmation
}

// GetPasswordConfirmationOk returns a tuple with the PasswordConfirmation field value
// and a boolean to check if the value has been set.
func (o *InlineObject5) GetPasswordConfirmationOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PasswordConfirmation, true
}

// SetPasswordConfirmation sets field value
func (o *InlineObject5) SetPasswordConfirmation(v string) {
	o.PasswordConfirmation = v
}

// GetPasswordAlgorithm returns the PasswordAlgorithm field value
func (o *InlineObject5) GetPasswordAlgorithm() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.PasswordAlgorithm
}

// GetPasswordAlgorithmOk returns a tuple with the PasswordAlgorithm field value
// and a boolean to check if the value has been set.
func (o *InlineObject5) GetPasswordAlgorithmOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PasswordAlgorithm, true
}

// SetPasswordAlgorithm sets field value
func (o *InlineObject5) SetPasswordAlgorithm(v string) {
	o.PasswordAlgorithm = v
}

// GetPasswordSalt returns the PasswordSalt field value if set, zero value otherwise.
func (o *InlineObject5) GetPasswordSalt() string {
	if o == nil || o.PasswordSalt == nil {
		var ret string
		return ret
	}
	return *o.PasswordSalt
}

// GetPasswordSaltOk returns a tuple with the PasswordSalt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject5) GetPasswordSaltOk() (*string, bool) {
	if o == nil || o.PasswordSalt == nil {
		return nil, false
	}
	return o.PasswordSalt, true
}

// HasPasswordSalt returns a boolean if a field has been set.
func (o *InlineObject5) HasPasswordSalt() bool {
	if o != nil && o.PasswordSalt != nil {
		return true
	}

	return false
}

// SetPasswordSalt gets a reference to the given string and assigns it to the PasswordSalt field.
func (o *InlineObject5) SetPasswordSalt(v string) {
	o.PasswordSalt = &v
}

func (o InlineObject5) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["password"] = o.Password
	}
	if true {
		toSerialize["password_confirmation"] = o.PasswordConfirmation
	}
	if true {
		toSerialize["password_algorithm"] = o.PasswordAlgorithm
	}
	if o.PasswordSalt != nil {
		toSerialize["password_salt"] = o.PasswordSalt
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject5 struct {
	value *InlineObject5
	isSet bool
}

func (v NullableInlineObject5) Get() *InlineObject5 {
	return v.value
}

func (v *NullableInlineObject5) Set(val *InlineObject5) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject5) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject5(val *InlineObject5) *NullableInlineObject5 {
	return &NullableInlineObject5{value: val, isSet: true}
}

func (v NullableInlineObject5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
