// Code generated by "openapi-codegen"; DO NOT EDIT.
/*
 * OneLogin API
 *
 * This is an administrative API for OneLogin customers
 *
 * API version: 1.1.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"encoding/json"
	"github.com/yacchi/go-onelogin-oas/models"
)

// LoginVerifyMfaResponseData struct for LoginVerifyMfaResponseData
type LoginVerifyMfaResponseData struct {
	Status *string `json:"status,omitempty"`
	User *ResponseUser `json:"user,omitempty"`
	ReturnToUrl *string `json:"return_to_url,omitempty"`
	ExpiresAt *string `json:"expires_at,omitempty"`
	SessionToken *string `json:"session_token,omitempty"`
}

// NewLoginVerifyMfaResponseData instantiates a new LoginVerifyMfaResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginVerifyMfaResponseData() *LoginVerifyMfaResponseData {
	this := LoginVerifyMfaResponseData{}
	return &this
}

// NewLoginVerifyMfaResponseDataWithDefaults instantiates a new LoginVerifyMfaResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginVerifyMfaResponseDataWithDefaults() *LoginVerifyMfaResponseData {
	this := LoginVerifyMfaResponseData{}
	return &this
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *LoginVerifyMfaResponseData) GetStatus() string {
	if o == nil || o.Status == nil {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginVerifyMfaResponseData) GetStatusOk() (*string, bool) {
	if o == nil || o.Status == nil {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *LoginVerifyMfaResponseData) HasStatus() bool {
	if o != nil && o.Status != nil {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *LoginVerifyMfaResponseData) SetStatus(v string) {
	o.Status = &v
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *LoginVerifyMfaResponseData) GetUser() ResponseUser {
	if o == nil || o.User == nil {
		var ret ResponseUser
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginVerifyMfaResponseData) GetUserOk() (*ResponseUser, bool) {
	if o == nil || o.User == nil {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *LoginVerifyMfaResponseData) HasUser() bool {
	if o != nil && o.User != nil {
		return true
	}

	return false
}

// SetUser gets a reference to the given ResponseUser and assigns it to the User field.
func (o *LoginVerifyMfaResponseData) SetUser(v ResponseUser) {
	o.User = &v
}

// GetReturnToUrl returns the ReturnToUrl field value if set, zero value otherwise.
func (o *LoginVerifyMfaResponseData) GetReturnToUrl() string {
	if o == nil || o.ReturnToUrl == nil {
		var ret string
		return ret
	}
	return *o.ReturnToUrl
}

// GetReturnToUrlOk returns a tuple with the ReturnToUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginVerifyMfaResponseData) GetReturnToUrlOk() (*string, bool) {
	if o == nil || o.ReturnToUrl == nil {
		return nil, false
	}
	return o.ReturnToUrl, true
}

// HasReturnToUrl returns a boolean if a field has been set.
func (o *LoginVerifyMfaResponseData) HasReturnToUrl() bool {
	if o != nil && o.ReturnToUrl != nil {
		return true
	}

	return false
}

// SetReturnToUrl gets a reference to the given string and assigns it to the ReturnToUrl field.
func (o *LoginVerifyMfaResponseData) SetReturnToUrl(v string) {
	o.ReturnToUrl = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise.
func (o *LoginVerifyMfaResponseData) GetExpiresAt() string {
	if o == nil || o.ExpiresAt == nil {
		var ret string
		return ret
	}
	return *o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginVerifyMfaResponseData) GetExpiresAtOk() (*string, bool) {
	if o == nil || o.ExpiresAt == nil {
		return nil, false
	}
	return o.ExpiresAt, true
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *LoginVerifyMfaResponseData) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt != nil {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given string and assigns it to the ExpiresAt field.
func (o *LoginVerifyMfaResponseData) SetExpiresAt(v string) {
	o.ExpiresAt = &v
}

// GetSessionToken returns the SessionToken field value if set, zero value otherwise.
func (o *LoginVerifyMfaResponseData) GetSessionToken() string {
	if o == nil || o.SessionToken == nil {
		var ret string
		return ret
	}
	return *o.SessionToken
}

// GetSessionTokenOk returns a tuple with the SessionToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginVerifyMfaResponseData) GetSessionTokenOk() (*string, bool) {
	if o == nil || o.SessionToken == nil {
		return nil, false
	}
	return o.SessionToken, true
}

// HasSessionToken returns a boolean if a field has been set.
func (o *LoginVerifyMfaResponseData) HasSessionToken() bool {
	if o != nil && o.SessionToken != nil {
		return true
	}

	return false
}

// SetSessionToken gets a reference to the given string and assigns it to the SessionToken field.
func (o *LoginVerifyMfaResponseData) SetSessionToken(v string) {
	o.SessionToken = &v
}

func (o LoginVerifyMfaResponseData) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Status != nil {
		toSerialize["status"] = o.Status
	}
	if o.User != nil {
		toSerialize["user"] = o.User
	}
	if o.ReturnToUrl != nil {
		toSerialize["return_to_url"] = o.ReturnToUrl
	}
	if o.ExpiresAt != nil {
		toSerialize["expires_at"] = o.ExpiresAt
	}
	if o.SessionToken != nil {
		toSerialize["session_token"] = o.SessionToken
	}
	return json.Marshal(toSerialize)
}

type NullableLoginVerifyMfaResponseData struct {
	value *LoginVerifyMfaResponseData
	isSet bool
}

func (v NullableLoginVerifyMfaResponseData) Get() *LoginVerifyMfaResponseData {
	return v.value
}

func (v *NullableLoginVerifyMfaResponseData) Set(val *LoginVerifyMfaResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginVerifyMfaResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginVerifyMfaResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginVerifyMfaResponseData(val *LoginVerifyMfaResponseData) *NullableLoginVerifyMfaResponseData {
	return &NullableLoginVerifyMfaResponseData{value: val, isSet: true}
}

func (v NullableLoginVerifyMfaResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginVerifyMfaResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
