// Code generated by "openapi-codegen"; DO NOT EDIT.
/*
 * OneLogin API
 *
 * This is an administrative API for OneLogin customers
 *
 * API version: 1.1.0-oas3
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import (
	"encoding/json"
)

// AssignPrivilegeRolesResponse struct for AssignPrivilegeRolesResponse
type AssignPrivilegeRolesResponse struct {
	Success *bool `json:"success,omitempty"`
}

// NewAssignPrivilegeRolesResponse instantiates a new AssignPrivilegeRolesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAssignPrivilegeRolesResponse() *AssignPrivilegeRolesResponse {
	this := AssignPrivilegeRolesResponse{}
	return &this
}

// NewAssignPrivilegeRolesResponseWithDefaults instantiates a new AssignPrivilegeRolesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAssignPrivilegeRolesResponseWithDefaults() *AssignPrivilegeRolesResponse {
	this := AssignPrivilegeRolesResponse{}
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *AssignPrivilegeRolesResponse) GetSuccess() bool {
	if o == nil || o.Success == nil {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AssignPrivilegeRolesResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || o.Success == nil {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *AssignPrivilegeRolesResponse) HasSuccess() bool {
	if o != nil && o.Success != nil {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *AssignPrivilegeRolesResponse) SetSuccess(v bool) {
	o.Success = &v
}

func (o AssignPrivilegeRolesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Success != nil {
		toSerialize["success"] = o.Success
	}
	return json.Marshal(toSerialize)
}

type NullableAssignPrivilegeRolesResponse struct {
	value *AssignPrivilegeRolesResponse
	isSet bool
}

func (v NullableAssignPrivilegeRolesResponse) Get() *AssignPrivilegeRolesResponse {
	return v.value
}

func (v *NullableAssignPrivilegeRolesResponse) Set(val *AssignPrivilegeRolesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAssignPrivilegeRolesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAssignPrivilegeRolesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAssignPrivilegeRolesResponse(val *AssignPrivilegeRolesResponse) *NullableAssignPrivilegeRolesResponse {
	return &NullableAssignPrivilegeRolesResponse{value: val, isSet: true}
}

func (v NullableAssignPrivilegeRolesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAssignPrivilegeRolesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
